export const FILE_UPLOAD_INIT = "FILE_UPLOAD_INIT";
export const FILE_UPLOAD_SUCCESS = "FILE_UPLOAD_SUCCESS";
export const FILE_UPLOAD_FAILURE = "FILE_UPLOAD_FAILURE";

export const UPDATE_FILE_DATA = "UPDATE_FILE_DATA";
export const UPDATE_FILE_DATA_SUCCESS = "UPDATE_FILE_DATA_SUCCESS";
export const UPDATE_FILE_DATA_FAILURE = "UPDATE_FILE_DATA_FAILURE";
